[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "gcc", "pkg-config", "postgresql", "libffi", "openssl"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python main.py"